# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotodo < Formula
  desc "A tiny, delicate todo CLI written in Go"
  homepage "https://github.com/yuxbao/gotodo"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.1.0/gotodo_1.1.0_darwin_amd64.tar.gz"
      sha256 "0f8f9f0f3a8e219a9006644dc9e26f57cfa09ba94b273a8f48e7a06316619018"

      def install
        bin.install "gotodo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.1.0/gotodo_1.1.0_darwin_arm64.tar.gz"
      sha256 "8e883f5ccc6017f06d6ee45f841b6f216eab820454f63c4913ab288d09fab6f9"

      def install
        bin.install "gotodo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.1.0/gotodo_1.1.0_linux_amd64.tar.gz"
      sha256 "003f2066dc0f9b34894baa6266590076d7698df5b50a1b91f75db637118982eb"
      def install
        bin.install "gotodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.1.0/gotodo_1.1.0_linux_arm64.tar.gz"
      sha256 "b478d46448b4d53460a62eeaefa18198412e3c14733a90923d29d853e6341b44"
      def install
        bin.install "gotodo"
      end
    end
  end

  test do
    system "#{bin}/gotodo", "--version"
    system "#{bin}/gotodo", "--help"
  end
end
