# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotodo < Formula
  desc "A tiny, delicate todo CLI written in Go"
  homepage "https://github.com/yuxbao/gotodo"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.2.1/gotodo_1.2.1_darwin_amd64.tar.gz"
      sha256 "2666ddbc8aa759b9a6b37c88a075bce9e823982603c129daf92f36d495164040"

      def install
        bin.install "gotodo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.2.1/gotodo_1.2.1_darwin_arm64.tar.gz"
      sha256 "1ebbbe9298598e031a367da4e74090e6ff67517525f24384d1248acdaeeec030"

      def install
        bin.install "gotodo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.2.1/gotodo_1.2.1_linux_amd64.tar.gz"
      sha256 "88e66e119db3cbfa1388fb29380ee314a799a92ca312a837d45c3b06d899ef6c"
      def install
        bin.install "gotodo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuxbao/gotodo/releases/download/v1.2.1/gotodo_1.2.1_linux_arm64.tar.gz"
      sha256 "1371260580bc15660bd1f9a54607239062bd4cca5d78ef472d35ca77ad63318b"
      def install
        bin.install "gotodo"
      end
    end
  end

  test do
    system "#{bin}/gotodo", "--version"
    system "#{bin}/gotodo", "--help"
  end
end
